config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tiras
  resources :tags, only: [:index, :show]
  authenticated :user do
  	root :to => "tiras#index", :as => "dashboard"  
  	
  end

  root :to => 'home#index'
  post '/', :to => 'home#index'
  get 'teo', :to => 'home#teo'
  get 'nuestras_voces', :to => 'home#voces'
  get 'archivo', :to => 'home#archivo'
  get 'colabora', :to => 'home#colabora'
  get 'tienda', :to => 'home#tienda'
   get 'etica', :to => 'home#etica'
   get 'aviso', :to => 'home#aviso'
   get 'terms', :to => 'home#terms'
   get 'blog', :to => 'home#blog'

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.has_role? :admin 
         can :manage, :all
         can :access, :rails_admin   # grant access to rails_admin
         can :dashboard              # grant access to the dashboard
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tira.rb
class Tira < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable

  def self.get_previous_tira(current_tira)   
     Tira.where("tiras.id < ? ", current_tira.id).order('created_at asc').last
  end


  def self.get_next_tira(current_tira)                    
    	Tira.where("tiras.id > ? ", current_tira.id).order('created_at asc').first
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tiras
  validates :terms_of_service, acceptance: true
   mount_uploader :image, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception| #check if the user acces was denied, redirects them to the root and shows an error alert
    redirect_to root_path, :alert => exception.message 
  end
 

  def after_sign_in_path_for(resource)  #Authorization process CanCan and rolify
    unless current_user.roles.first.nil?
      case current_user.roles.first.name #Checks the role of current user
        when 'admin'  #If the role is admin it sends them to users_path, which is the pseudo admin screen
          rails_admin_path
        when 'autor' #if the role is bold_moves, it first checks that there is still a stripe subscription for that user and then redirects to bold_moves path (workouts); if not, it makes the role of the user nil revoking him of all access 
          root_path
        else #if there is no role, user is redirected to the root
          
          destroy_user_session_path
      end
    else

        destroy_user_session_path
    end

    
  end

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :cargo, :inst, :sitio, :bio, :zona, :terms_of_service) }
             devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :cargo, :inst, :sitio, :bio, :zona, :current_password) }
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'rss'
  def index
    if params[:id]
      @tira = Tira.where(aprobado: true).find(params[:id])
    else
      @tira = Tira.where(aprobado: true).last  
    end
  	if params[:like]
      @tira = Tira.find(params[:id])
      @tira.likes=@tira.likes+1
      @tira.save
    elsif params[:dislike]
      @tira.dislikes=@tira.dislikes+1
      @tira.save
    end
    
   
  end

  

  def archivo
    @tiras = Tira.where(aprobado: true).all
  end

  def voces
    @users = User.all
    
  end
   

  def tienda
  end
  def teo
  end
  def blog
    begin
       @latest_blog_posts = RSS::Parser.parse(open('https://teophiloequipo.wordpress.com/feed/').read, false).items[0..2]
     rescue
       # Do nothing, just continue.  The view will skip the blog section if the feed is nil.
       @latest_blog_posts = nil
     end
    
  end
  def etica
  end
  def colabora
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @tiras = Tira.tagged_with(@tag.name)
  end
end

app/controllers/tiras_controller.rb
class TirasController < ApplicationController
  before_action :set_tira, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @user = current_user
    @tiras = @user.tiras.all
    
  end

  def show
    
  end

  def new
    @tira = Tira.new
    @user = current_user
    
  end

  def edit
    @user = current_user
  end

  def create
    @tira = Tira.new(tira_params)
    @tira.save
    respond_to do |format|
      if @tira.save
        format.html { redirect_to tiras_path, notice: 'Tira was successfully created.' }
        format.json { render :show, status: :created, location: @tira }
      else
        format.html { render :new }
        format.json { render json: @tira.errors, status: :unprocessable_entity }
      end
    end
   
  end

  def update
    @tira.update(tira_params)
    respond_to do |format|
      if @tira.update(tira_params)
        format.html { redirect_to tiras_path, notice: 'Tira was successfully updated.' }
        format.json { render :show, status: :ok, location: @tira }
      else
        format.html { render :edit }
        format.json { render json: @tira.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def destroy
    @tira.destroy
    respond_to do |format|
      format.html { redirect_to tiras_url, notice: 'tira was successfully destroyed.' }
      format.json { head :no_content }
    end
   
  end

  private
    def set_tira
      @tira = Tira.find(params[:id])
    end

    def tira_params
      params.require(:tira).permit(:user_id, :titulo, :text1, :text2, :text3, :text4, :text5, :text6, :dia, :mes, :ano, :aprobado, :personaje_cuadro1, :personaje_cuadro2, :personaje_cuadro3, :personaje_cuadro4, :personaje_cuadro5, :personaje_cuadro6,:texto_personaje_cuadro1, :texto_personaje_cuadro2, :texto_personaje_cuadro3, :texto_personaje_cuadro4, :texto_personaje_cuadro5, :texto_personaje_cuadro6, :tag_list, :likes, :dislikes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tiras_helper.rb
module TirasHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/acts_as_taggable_on/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/acts_as_taggable_on/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @tiras %></div>

app/views/home/archivo.html.erb
<div class="large-4 columns" style="margin-left: 35%;">

<div class="centersection">
<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Título</th>
            <th colspan="1"></th>

    </tr>
  </thead>

  <tbody>
    <% @tiras.each do |tira| %>
      <tr>
      	<td><%= tira.created_at.strftime('%F') %></td>
        <td><%= tira.titulo %></td>
        <td><%=form_tag root_path, :method => 'get' do %>
				<%=hidden_field_tag :id, tira.id %>
				<%=submit_tag "Leer Ahora", :name =>nil, :class => "button" %> 
			<% end%>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%=link_to "Regresar", root_path%>
</div>
</div>

app/views/home/aviso.html.erb
<div class="titleteo2">Aviso de Privacidad</div>

	<p class="pmision">Para Teophilo.com (en lo sucesivo “Teophilo”), el tratamiento obligado, honesto, legítimo y controlado de los datos personales de todo usuario son de suma importancia para mantener el control interno y alcanzar los objetivos corporativos, así como mantener nuestro compromiso con la privacidad de los usuarios.</p>

<div class="titleteo">I. Responsabilidad en el tratamiento de los datos personales.</div>
<p class="pmision">Como empresa fidedigna, Teophilo se responsabiliza del uso interno y protección de datos personales que vayamos recabando como parte de nuestro proceso de inclusión de todo usuario, y los tratará de conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo “Ley de Datos”).</p>

<div class="titleteo">II. Contacto</div>
<p class="pmision">Cualquier usuario tiene la capacidad de tratar todo lo relacionado con la protección de sus datos personales. Para contactarnos, usted deberá enviar un correo electrónico a larriva@teophilo.com; o en su defecto, aldaco@teophilo.com</p>

<div class="titleteo">III. Recolección de datos personales</div>
<p class="pmision">Para fines internos de la corporación (establecidos en este aviso de privacidad), recabaremos los siguientes datos personales de todo usuario:</p>

<ul class="pmision">
    <li>Nombre completo</li>
    <li>Edad</li>
    <li>Género</li>
    <li>Lugar y fecha de nacimiento</li>
    <li>Nivel de estudios (Especificar carrera universitaria)</li>
    <li>Lugar de estudios</li>
    <li>Teléfono celular</li>
    <li>Ocupación</li>

</ul>

<p class="pmision">NO pediremos a los usuarios datos personales sensibles. Ley de Datos define a los datos personales sensibles de la siguiente manera:</p>

<p class="pmision2">Aquellos datos personales que afecten a la esfera más íntima de su titular, o cuya utilización indebida pueda dar origen a discriminación o conlleve un riesgo grave para éste. En particular, se consideran sensibles aquellos que puedan revelar aspectos como origen racial o étnico, estado de salud presente y futuro,información genética, creencias religiosas, filosóficas y morales, afiliación sindical, opiniones políticas, preferencia sexual.</p>

<p class="pmision">Si Teophilo llegara a requerir en un momento dado alguno de los datos mencionados anteriormente, el usuario tendrá que autorizarlo con anterioridad firmando este Aviso de Privacidad.</p>

<div class="titleteo"> IV. Uso de los datos personales</div>
<p class="pmision">Teophilo hará uso de los datos personales con los siguientes fines:</p>

<p class="pmision">a) Uso de los datos personales para solicitud de empleo en Teophilo.</p>

<ul class="pmision" style="margin-left: 20%;">
    <li>Ponerse en contacto con con cualquier solicitante de empleo por las distintas vías de comunicación.</li>
    <li>Inscribirlo y darlo de alta en nuestro sistema, ya sea como autor o como colaborador.</li>
    <li>Se le efectuarán exámenes psicométricos y de habilidades que se evaluarán de acuerdo a nuestro proceso de selección</li>
</ul>

<p class="pmision">b) Uso de los datos personales para todo usuario.</p>
<ul class="pmision" style="margin-left: 20%;">
<li>Crear un perfil de usuario en Teophilo.</li>
<li>Identificarlo y contactarlo</li>
<li>Mantener un control estadístico interno de la corporación.</li>
<li>Se le enviarán encuestas para conocer su satisfacción con la plataforma de forma periódica.</li>
<li>Enviar publicidad sobre contenido y mercancía.</li>
</ul>

<div class="titleteo"> V. Cambios en el Aviso</div>
<p class="pmision">Teophilo será capaz de hacer cambios en cualquiera de los datos* de todo tipo de usuario con el previo consentimiento del mismo por medio de cualquier vía de comunicación*</p>




<div class="titleteo"> VI. Seguridad</div>
<p class="pmision">Sólamente el personal de Teophilo está autorizado y capacitado para tratar los datos personales de cualquier tipo de usuario. El incumplimiento de esto violaría la Ley de Datos.</p>


	
<div class="titleteo"> VII. IFAI</div>
<p class="pmision">En caso de que cualquier usuario considere que sus datos hayan sido violados o lesionados por el personal de Teophilo conforme a la Ley de Datos, podrá interponer su inconformidad o denuncia ante el Instituto Federal de Acceso a la Información y Protección de Datos.</p>

app/views/home/blog.html.erb
<h1  class="title_section">ÚLTIMAS ENTRADAS DE BLOG</h1>
<% unless @latest_blog_posts.nil? %>
 
 <ul class="pmision">
  <% @latest_blog_posts.each do |post| %>
   <% if nil != post && post.respond_to?(:pubDate) %>
    <li>
     <%= link_to post.title, post.link, :target => "_blank" %>
     (<%= time_ago_in_words(post.pubDate) %> ago via Teophilo Blog)
    </li>
   <% end %>
  <% end %>
 </ul>
<% else %>
 <p>
  <em>No hay entradas de blog que mostrar.</em>
 </p>
<% end %>

app/views/home/colabora.html.erb
<div class="shop"></div>
<div class="share"></div>
<div class="buscar"></div>
<div class="login"><%= link_to 'Sign in', new_user_session_path %></div>
<div class="logotop"></div>

<ul class="nav">
	<li>MEMARIOS </li>
	<li><a href="/tienda">TIENDA</a></li>
	<li>BLOGS</li>
	<li>NUESTRAS VOCES</li>
	<li><a href="/etica">CÓDIGO DE ÉTICA</a></li>
	<li><a href="/colabora">COLABORA CON NOSOTROS</a></li>
	<li><a href="/teo">TEO</a></li>
</ul>
<div class="headerline"></div>

	<div class="colabora"></div>

<div class="footerline">
	<ul class="nav-bottom">
	<li class="liteo"><a href="/">TEOPHILO</a></li>
	<li>MEMARIOS </li>
	<li><a href="/tienda">TIENDA</a></li>
	<li>BLOGS</li>
	<li>NUESTRAS VOCES</li>
	<li><a href="/etica">CÓDIGO DE ÉTICA</a></li>
	<li><a href="/teo">TEO</a></li>
	<li><a href="/colabora">COLABORA CON NOSOTROS</a></li>
</ul>
</div>

app/views/home/etica.html.erb
<div class="mision">
	<div class="titleteo2"> CÓDIGO DE ÉTICA</div>
	<p class="pmision">El siguiente documento funge como una guía de referencia de comportamiento para nuestros miembros. En Teophilo consideramos el respeto, la pluralidad, honestidad e integridad como ejes fundamentales para la construcción de una sociedad fraterna, justa y equitativa. Asimismo estamos comprometidos con el desarrollo de ésta sociedad y nos reconocemos como actores fundamentales en el país que deseamos construir. Por ello debemos asumir una actitud proactiva y apasionada ya que es premisa nuestra exhortarnos constantemente a encontrar y proponer soluciones a los problemas de la realidad mexicana.<br><br>

	En virtud de ésta construcción es necesario establecer ciertas normas básicas de convivencia cotidiana con el fin de edificar un espacio dónde se reflejen nuestros valores y principios. <br><br>

</div>


<div class="mision">
<div class="titleteo">SOBRE NUESTRO COMPROMISO CON LA SOCIEDAD</div>

<p class="pmision">Teophilo al ser un proyecto enteramente universitario reconoce su alcance y capacidad de influencia. Ésta deberá ser utilizada para mejorar el entorno social y promover conductas de crítica social y  participación ciudadana al potencializar la voz de miles de mexicanos que desean expresar sus ideas, emociones o sentir sobre los problemas de México a través del arte. Como ciudadanos de éste país reconocemos nuestra obligación y extendemos nuestro compromiso de trabajar por la sociedad al elaborar una crítica inteligente y propositiva que contribuya a concientizar a un mayor número de individuos e incentivarlos a ser agentes de cambio.</p></div>
 

<div class="mision">
<div class="titleteo">SOBRE NUESTRO COMPROMISO CON NUESTROS COLABORADORES</div>

<p class="pmision">Teophilo es un espacio construido a través de la voz de miles de mexicanos a los cuales reconoce como su razón de ser. Por ello, garantizamos un ambiente de respeto y estamos comprometidos a potencializar sus talentos otorgándoles un espacio dónde puedan expresarse libremente. También creemos firmemente que una sociedad fraterna se construye alentado e involucrando a los individuos en el ejercicio de su ciudadanía por lo que constantemente se invita a nuevos colaboradores a ser parte de la gran familia de Teophilo.</p></div>


<div class="mision">
<div class="titleteo">SOBRE NUESTRAS OBLIGACIONES</div>

<p class="pmision">Los miembros que integran Teophilo deberán mantenerse al margen de externar opiniones que comprometan la imagen y la postura del medio. Todo comentario realizado fuera del área que compete al sitio es responsabilidad de quien lo emite. <br><br>

Asimismo tienen prohibido favorecer el interés de grupos de poder ya que toda influencia ajena el ejercicio libre y objetivo será severamente castigada, así como es deber de los miembros informar cualquier situación que pudiese suscitar un conflicto de intereses. <br><br>

Asumimos el compromiso de responder dudas, comentarios o sugerencias que pudieran surgir de parte de los usuarios sobre el contenido de la página. <br><br>

Finalmente los miembros de Teophilo no deberán ceder ante provocaciones y altercados propiciados por algún externo, y se manejarán siempre con respeto y tolerancia sobre la diversidad de opiniones.
</p></div>

<div class="mision">
<div class="titleteo">SOBRE NUESTROS VALORES</div>

<div class="nombrepersonaje">INTEGRIDAD</div>
<p class="pmision">Nuestro encargo es el de siempre basar nuestras acciones en un marco coherente de principios siendo conscientes del impacto de nuestras decisiones. </p>


<div class="nombrepersonaje">RESPETO</div>
<p class="pmision">El respeto es una actitud y toda buena relación debe construirse en base a ella. Por eso se debemos asegurarnos de que no se cometan faltas hacia la valiosa individualidad de las personas. </p>


<div class="nombrepersonaje">PLURALIDAD</div>
<p class="pmision">Acorde con la filosofía de la página, no podemos permitir que exista ningún tipo de discriminación ya sea por sexo, edad, raza, preferencia sexual, incapacidad o cualquier otra condición que fracture las normas de convivencia. </p></div>



<div class="mision">
<div class="titleteo">SOBRE LAS NORMAS DE PARTICIPACIÓN</div>	

<p class="pmision">En Teophilo procuramos establecer un diálogo horizontal con el fin de fomentar la crítica social y las propuestas. Con el fin fomentar la diversidad y promover un discurso incluyente queda estrictamente prohibido hacer ataques personales a grupos culturales, sociales, políticos, étnicos, de género o preferencial sexual. Se pueden tocar temas relacionados a estos grupos pero buscando siempre la crítica y construcción sobre las ideas y no personas. <br><br>

Teophilo no es responsable del contenido que seleccionen los colaboradores; les otorga libertad en la elección del tema siempre y cuando no violente de alguna forma la integridad de sus lectores.
<br><br>
Se debe procurar no usar palabras altisonantes,  lenguaje abusivo o comentarios irrespetuosos a menos de que sea necesario y siendo utilizado como herramienta de construcción y no como ofensa. <br><br>

Es responsabilidad de los colaboradores ofrecer una temática que responda a las problemáticas y necesidades de México y no sólo de un sector o atendiendo los gustos propios. </p></div>

app/views/home/index.html.erb
<%= render "comic"%>

<div class="row">
	<div class="large-5 medium-5 small-5 columns">
		<div class="colaboras">
			COLABORA
		</div>
	</div>
	<div class="large-2 medium-2 small-2 columns">
		
	</div>
	<div class="large-5 medium-5 small-5 columns">
		<div class="colaboras">
			¡ANÚNCIATE!
		</div>
	</div>
</div>
<div class="row">
	<div class="large-5 medium-5 small-5 columns">
		<%= image_tag("teocolabora.png", :class => "img_tbl") %>
	</div>
	<div class="large-2 medium-2 small-2columns">
		
	</div>
	<div class="large-5 medium-5 small-5 columns">
		<%= image_tag("teoanuncia.png" , :class => "img_tbl") %>
	</div>
</div>

<div class="row">
	<div class="large-5 medium-5 small-5 columns">
		<p  class="table_text">Si quieres formar parte del equipo / escribir / dibujar / colaborar de alguna forma con Teo, manda un correo a aldaco@teophilo.com y nos ponemos en contacto.</p> 
	</div>
	<div class="large-2 medium-2 small-2 columns">
		
	</div>
	<div class="large-5 medium-5 small-5 columns">
		<p class="table_text">¡Manda un correo a larriva@teophilo.com y me pongo en contacto contigo!</p>
	</div>
</div>

<div class="footerline">
	<img src="assets/teofooter.png">
	<div class="footer_mision">MISIÓN</div>
	<div class="footer_text">
		<p class="table_text2">Teophilo pretende crear un espacio plural –de ideas y arte– donde las idiosincrasias y propuestas de la diversidad nacional coexistan y construyan una sociedad más fraterna, libre y equitativa.</p>
		<p class="table_text2">Elizabeth Anderson (1999) en “What is the Point of Equality”: </p>
		<i class="table_text2">El igualitarismo (egalitarianism) debe reflejar una visión generosa, humana, y cosmopolita de una sociedad que reconozca a las personas como iguales en toda su diversidad. Se debe promover acuerdos institucionales que permitan la diversidad de talentos, las aspiraciones, las funciones y las culturas de las personas en beneficio de todos y que se reconozcan como de beneficio mutuo.</i>
		</div>
</div>

app/views/home/tienda.html.erb
<div class="shop"></div>
<div class="share"></div>
<div class="buscar"></div>
<div class="login"><%= link_to 'Sign in', new_user_session_path %></div>
<div class="logotop"></div>

<ul class="nav">
	<li>MEMARIOS </li>
	<li><a href="/tienda">TIENDA</a></li>
	<li>BLOGS</li>
	<li>NUESTRAS VOCES</li>
	<li><a href="/etica">CÓDIGO DE ÉTICA</a></li>
	<li><a href="/colabora">COLABORA CON NOSOTROS</a></li>
	<li><a href="/teo">TEO</a></li>
</ul>
<div class="headerline"></div>

	<div class="proximamente"></div>

<div class="footerline">
	<ul class="nav-bottom">
	<li class="liteo"><a href="/">TEOPHILO</a></li>
	<li>MEMARIOS </li>
	<li><a href="/tienda">TIENDA</a></li>
	<li>BLOGS</li>
	<li>NUESTRAS VOCES</li>
	<li><a href="/etica">CÓDIGO DE ÉTICA</a></li>
	<li><a href="/teo">TEO</a></li>
	<li><a href="/colabora">COLABORA CON NOSOTROS</a></li>
</ul>
</div>

app/views/home/voces.html.erb
<div class="cont_margin" >
	<h2 class="title_section">NUESTROS COLABORADORES</h2>
	<%@users.each do |u|%>
		<div style="margin-top: 2%; margin-bottom: 1%; position:relative; left: 5%;">
			<% if (u.roles.first != nil) %>
				<div class="sideimage"><%=image_tag u.image %></div>
			<% end %>
			<div class="voces"><h3 class="nombre_autor_voces"><%= u.first_name %> <%= u.last_name %></h3>
			<h6 class="descrip_voces"><%= u.cargo %> @ <%= u.inst %></h6>
			<p> <%= u.bio %></p>
			<a href="http://<%=u.sitio %>"><%=u.sitio %></a></div>
			
		</div>
	<% end %>
</div>

app/views/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<div class="large-4 columns" style="margin-left: 35%;">
<div class="centersection">
	<h1>Tiras con el tag: <%= @tag.name %></h1>
	<table>
	  <thead>
	    <tr>
	      <th>Fecha</th>
	      <th>Título</th>
	            <th colspan="1"></th>

	    </tr>
	  </thead>

	  <tbody>
	    <% @tiras.each do |tira| %>
	      <tr>
	      	<td><%= tira.created_at.strftime('%F') %></td>
	        <td><%= tira.titulo %></td>
	        <td><%=form_tag root_path, :method => 'get' do %>
					<%=hidden_field_tag :id, tira.id %>
					<%=submit_tag "Leer Ahora", :name =>nil, :class => "button" %> 
				<% end%>
			</td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>
</div>

app/views/tiras/index.html.erb
<div class="large-4 columns" style="margin-left: 35%;">
<div class="indexlist">
<h1>Archivo de tiras</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Título</th>
      <th>Fecha</th>
      <th>Etiquetas</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @tiras.each do |tira| %>
      <tr>
        <td><%= tira.user.first_name %></td>
        <td><%= tira.titulo %></td>
        <td><%= tira.created_at.strftime('%F')%></td>
        <td><%= render tira.tags %></td>
        <td><%= link_to 'Editar', edit_tira_path(tira) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @user.roles.first.name == "admin" %>
<%= link_to 'Panel de administrador', rails_admin_path %><br>
<% end %>
<%= link_to 'Crear Nueva Tira', new_tira_path %><br>
<%= link_to 'Editar Perfil', edit_registration_path(current_user) %><br>
<%= link_to 'Logout', destroy_user_session_path, method: :get %>
</div>
</div>

app/views/tiras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @tira.user %>
</p>

<p>
  <strong>Título:</strong>
  <%= @tira.titulo %>
</p>

<p>
  <strong>Texto cuadro 1:</strong>
  <%= @tira.text1 %>
</p>

<p>
  <strong>Texto cuadro 2:</strong>
  <%= @tira.text2 %>
</p>

<p>
  <strong>Texto cuadro 3:</strong>
  <%= @tira.text3 %>
</p>

<p>
  <strong>Texto cuadro 4:</strong>
  <%= @tira.text4 %>
</p>

<p>
  <strong>Texto cuadro 5:</strong>
  <%= @tira.text5 %>
</p>

<p>
  <strong>Texto cuadro 6:</strong>
  <%= @tira.text6 %>
</p>

<p>
  <strong>Día que será exhibido:</strong>
  <%= @tira.dia %>
</p>

<p>
  <strong>Mes:</strong>
  <%= @tira.mes %>
</p>

<p>
  <strong>Año:</strong>
  <%= @tira.ano %>
</p>

<p>
  <strong>Aprobado:</strong>
  <%= @tira.aprobado %>
</p>
<%= link_to 'Edit', edit_tira_path(@tira) %> |
<%= link_to 'Back', tiras_path %>